version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: profileDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      ENV_USEDB: postgres
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: Admin123
      PG_DATABASE: profileDB
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  pgdata:
    driver: local
